// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPQ2NHeZ5elWNmQpuwpnHNkJK2O4b8FOI',
    appId: '1:766516080805:web:c438073b22d47a4af91d4c',
    messagingSenderId: '766516080805',
    projectId: 'ingeniusly-1',
    authDomain: 'ingeniusly-1.firebaseapp.com',
    storageBucket: 'ingeniusly-1.appspot.com',
    measurementId: 'G-C4NT7G0PK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRp4gktK9F7tNU_WMZ4UsSkk4xnKiyEFs',
    appId: '1:766516080805:android:82fdca51715b729ef91d4c',
    messagingSenderId: '766516080805',
    projectId: 'ingeniusly-1',
    storageBucket: 'ingeniusly-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFyYPKOvS6_nLCwdgrUgD0jNPuKG3YRM',
    appId: '1:766516080805:ios:d56571e0940d8b00f91d4c',
    messagingSenderId: '766516080805',
    projectId: 'ingeniusly-1',
    storageBucket: 'ingeniusly-1.appspot.com',
    iosBundleId: 'com.example.ingeniusly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoFyYPKOvS6_nLCwdgrUgD0jNPuKG3YRM',
    appId: '1:766516080805:ios:d56571e0940d8b00f91d4c',
    messagingSenderId: '766516080805',
    projectId: 'ingeniusly-1',
    storageBucket: 'ingeniusly-1.appspot.com',
    iosBundleId: 'com.example.ingeniusly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPQ2NHeZ5elWNmQpuwpnHNkJK2O4b8FOI',
    appId: '1:766516080805:web:9eebd5de6b11470df91d4c',
    messagingSenderId: '766516080805',
    projectId: 'ingeniusly-1',
    authDomain: 'ingeniusly-1.firebaseapp.com',
    storageBucket: 'ingeniusly-1.appspot.com',
    measurementId: 'G-8YNXD4ZXEK',
  );
}